name: Post

on:
  push:
    branches:
      - master
  # schedule:
  #   - cron: '0 21 * * *' # Daily at 21:00 UTC (07:00 AEST)

defaults:
  run:
    shell: bash

jobs:
  post:
    name: Post
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          pip install praw

      - name: Run
        run: |
          python post-vax-to-reddit.py \
          '${{ secrets.REDDIT_CLIENT_ID }}' \
          '${{ secrets.REDDIT_CLIENT_SECRET }}' \
          '${{ secrets.REDDIT_PASSWORD }}'
