name: NSW update and post

on:
  # push:
  #   branches:
  #     - master
  schedule:
    - cron: '30 00 * * *' # Daily at 00:30 UTC (10:30 AEST)

defaults:
  run:
    shell: bash

jobs:
  nswupdate:
    name: Update and post
    runs-on: ubuntu-latest
    env:
      MPLBACKEND: Agg
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          pip install numpy scipy matplotlib pandas lxml requests praw

      - name: Update
        run: |
          if python wait-for-nsw-update.py | grep "ready!"; then
            ./nsw.sh
          fi

      - name: Git pull
        run: git pull --rebase --autostash

      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: NSW update
          
      - name: Post
        run: |
          python post-nsw-to-reddit.py \
          '${{ secrets.REDDIT_CLIENT_ID }}' \
          '${{ secrets.REDDIT_CLIENT_SECRET }}' \
          '${{ secrets.REDDIT_PASSWORD }}'



