name: Update

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0-59/30 * * * *' # Every 30 minutes
    # - cron: '0 6 * * *' # Daily at 06:00 UTC

defaults:
  run:
    shell: bash


jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    env:
      MPLBACKEND: Agg
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          pip install numpy scipy matplotlib pandas

      - name: Run
        run: |
          if ./check-vax-outdated | grep "outdated!"; then
            python aus_vax.py
            python aus_vax.py project
          fi

      - name: Git pull
        run: git pull --rebase --autostash

      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Vax update
