name: Vax Update 

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  vaxupdate:
    name: Vax Update
    runs-on: ubuntu-latest
    env:
      MPLBACKEND: Agg
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          pip install numpy scipy matplotlib pandas requests

      - name: Run
        run: |
          if python check-vax-outdated.py | grep "outdated!"; then
            python aus_vax.py
            python aus_vax.py project
          fi
      
      - name: "Replace invalid 'book' value with 'normal' in SVGs"
        run: find **/*.svg | xargs -I"{}" sed 's/\"book\"/\"normal\"/w {}' {}
        
      - name: "Remove invalid font-style=bold from SVGs"
        run: find **/*.svg | xargs -I"{}" sed 's/font-style=\"bold\"//w {}' {}

      - name: Install svgcleaner crate
        uses: actions-rs/install@v0.1
        with:
          crate: svgcleaner
          version: latest
          use-tool-cache: true

      - name: "Optimize SVGs"
        run: find **/*.svg | xargs -I"{}" svgcleaner {} {}

      - name: Git pull
        run: git pull --rebase --autostash

      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Vax update
