name: Update

on:
  # push:
  #   branches:
  #     - master
  schedule:
    # - cron: '0-59/5 * * * *' # Every 5 minutes
    - cron: "0 6 * * *" # Daily at 06:00 UTC

defaults:
  run:
    shell: bash

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    env:
      MPLBACKEND: SVG
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          pip install numpy scipy matplotlib pandas uncertainties

      - name: Install svgcleaner crate
        uses: actions-rs/install@v0.1
        with:
          crate: svgcleaner
          version: latest
          use-tool-cache: true

      - name: Run
        run: |
          python covid.py
          python covid.py US
          svgcleaner COVID.svg COVID_o.svg
          mv COVID_o.svg COVID.svg
          svgcleaner COVID_US.svg COVID_US_o.svg
          mv COVID_US_o.svg COVID_US.svg

      - name: Git pull
        run: git pull --rebase --autostash

      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Automatic Update
